# Generated by Django 3.2.22 on 2023-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(
                default="../default_post_eji6md", upload_to="images/"
            ),
        ),
    ]
